# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CostEstimate:
    uses: TheCloudTheory/arm-estimator/.github/workflows/estimateFromUrl.yml@main
    with:
      rg: 'MyResourceGroup'
      environment: '' #Use empty string for repo level secrets
      templateFileURL: https://github.com/Azure/AKS-Construction/releases/download/0.9.4/main.json
      templateParamFileURL: https://raw.githubusercontent.com/Azure/AKS-Construction/main/.github/workflows_dep/AksDeploy-Private.parameters.json
    secrets:
      AZURE_CLIENT_ID: 1a7767b4-3f1e-4206-8fc1-356fa972fb06
      AZURE_TENANT_ID: 3a9d1200-d069-426a-a1cc-9b6a63dfb787
      AZURE_SUBSCRIPTION_ID: d74077ab-d4e2-4134-b162-594958b74c0b
